### ISSUE TITLE
project fails to run on gradle

### ISSUE THREAD

**Issue by saikrishna321** [saikrishna321/AppiumTestDistribution#306]
currently all the artifacts are generated inside target folder which holds good for maven, for gradle project its always build. we should make the artifact path configurable.

**Comment by hariharanwebmail** [comment]
Fixed by accepting OUTPUT_DIRECTORY as env parameter.

https://github.com/saikrishna321/AppiumTestDistribution/commit/e31a24c88e6c014b712995a70ed98cd4b6ccd34a

This helps in running on gradle build system. But for future need to consider someone giving absolute file path. Need to get rid of System.getenv("user.dir") from source code in these areas.
