### ISSUE TITLE
Screenshots not shown in ExtentReport

### ISSUE THREAD

**Issue by RatkoD** [saikrishna321/AppiumTestDistribution#70]
There is a bug with the links to the screenshots in the extentreport. The problem is that the timestamp is not concatenated to the screenshot filename. Screenshots are taken and in folder, but the links to them are wrong.

<img width="1100" alt="screen-shot-2016-06-13-at-08 25 00" src="https://cloud.githubusercontent.com/assets/18040695/16003073/30fd3064-315b-11e6-80b7-04e063207156.png">

<img width="989" alt="screen-shot-2016-06-13-at-08 33 27" src="https://cloud.githubusercontent.com/assets/18040695/16003071/30fc46b8-315b-11e6-80ed-4122793eb911.png">

<img width="1304" alt="screen-shot-2016-06-13-at-08 35 08" src="https://cloud.githubusercontent.com/assets/18040695/16003072/30fd257e-315b-11e6-838b-a10f3c3db9a8.png">

**Comment by nkrishnac-rpx** [comment]
@saikrishna321 
This issue is because in screenShotAndFrame method status is passed as 1 from calling method and we have to update failedScreen string variable to 
System.getProperty("user.dir") + "/target/screenshot/" + platform + "/"
                + device_udid.replaceAll("\\W", "_") + "/" + className + "/" + methodName + "/" + model + "_"
                + methodName + "_failed" + ".png";

Can i checkin it changes.

**Comment by saikrishna321** [comment]
@nkrishnac-rpx 
https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java#L329

this line picks the status from the test execution run.

The reason for sending the status as 1 in this method(https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumParallelTest.java#L568) is because user can capture screenshot during execution using captureScreenShot() method, Ideally we are working on getting a debug report which will show u all the screenshots captured in nexus5 device n forth.

@RatkoD with the updated code r u still seeing this issue ?

**Comment by RatkoD** [comment]
Nope, it's working now, the screenshot is displayed.
